default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: webshop_development
  username: postgres
  password: password

test:
  <<: *default
  database: webshop_test
  username: postgres
  password: password

production:
  <<: *default
  database: webshop_production
  username: postgres
  password: password